### ISSUE TITLE
Game gets back to the move in the same state on 'hit' and then throws on 'stand'.

### ISSUE THREAD

**Issue by NikitaZ** [CzJLee/Blackjack#1]
Dealing cards...
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?: h
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?: hit
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?: hit
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?: Hit
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?:
Hit or Stand?: hit
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?: hit
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?: hit
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
Hit or Stand?: stand
Dealer's Hand: Q♥, ??
Christian's Hand: 4♣, K♦
Christian's Hand Value: 14
All players have finished their turn.
Dealer's turn...
Dealer's Hand: Q♥, J♥
Dealer's Hand Value: 20
Determining winners...
[0]
GAME OVER

Dealing cards...
Traceback (most recent call last):
  File "play.py", line 10, in <module>
    print(bj.new_round())
  File "/Users/nikitazinoviev/work/games/py/Blackjack/game.py", line 136, in new_round
    self.print_hand_dealer()
  File "/Users/nikitazinoviev/work/games/py/Blackjack/game.py", line 71, in print_hand_dealer
    print(f"Dealer's Hand: {values_char[self.dealer.hand.cards[0].value]}{suits_char[self.dealer.hand.cards[0].suit]}, ??")

This game has very nice text presentation!! Superb!

**Comment by CzJLee** [comment]
Hi Nikita, thank you for your comment. This is a project that I started but never finished. Things are expected to be broken. 

I should archive this repo. Thank you.
